### ISSUE TITLE
minishift addons apply [addon/name] -- Error applying 

### ISSUE THREAD

**Issue by edmacabebe** [minishift/minishift-addons#105]
minishift addons apply che

Error applying the add-on: The specified path to the kube config '/Users/myname/.minishift/profiles/local-cluster-xyz/machines/local-cluster-xyz_kubeconfig' does not exist

**Comment by budhrg** [comment]
> Error applying the add-on: The specified path to the kube config '/Users/myname/.minishift/profiles/local-cluster-xyz/machines/local-cluster-xyz_kubeconfig' does not exist

@edmacabebe , you `minishift start` didn't happen successfully. 

Could you try again with 
```
$ minishift delete -f
$ rm -rf /Users/myname/.minishift/profiles/local-cluster-xyz
$ minishift start --profile local-cluster-xyz
```

**Comment by edmacabebe** [comment]
Thanks @budhrg , it worked!

**Comment by budhrg** [comment]
Closing as par your comment.
