### ISSUE TITLE
Dead link in che addon README

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift-addons#122]
Text link `Deploy Che on Minishift` now point to https://www.eclipse.org/che/docs/6/che/docs/openshift-single-user.html which gives 404. This is probably due to fact that Che switched to v6 as default in documentation. Correct link now is: https://www.eclipse.org/che/docs/openshift-single-user.html

**Comment by LalatenduMohanty** [comment]
Resolved by #128
