### ISSUE TITLE
Add-on to create HTPasswdIdentityProvider

### ISSUE THREAD

**Issue by kameshsampath** [minishift/minishift-addons#133]
With the new minishift feature allowing the users to connect to the Cloud instances, it would be worth allowing the user to change the default all password identity provider to something bit secured like the HTPasswdIdentityProvider.

This requires the minishift to have `httpd-tools` or similar package to be installed and persisted with the minishift instance.

https://github.com/minishift/minishift/issues/390

**Comment by gbraad** [comment]
@minishift/minishift-dev WDYT? this is something I would to see, but we have to be cautious not to become a new way to install a production-like cluster.

**Comment by gbraad** [comment]
https://medium.com/@kamesh_sampath/identify-yourself-on-minishift-c85f5bf8ba7d

**Comment by LalatenduMohanty** [comment]
IMO we should make it a default add-on.

**Comment by kameshsampath** [comment]
Optionally we should throw this option out to the user when connecting the could instance via minishift, which can be of better developer experience cautioning the user that he is with default AllowAllPasswordIdentityProvider and need to change to  something secured identity provider.

**Comment by gbraad** [comment]
https://github.com/minishift/minishift-centos-iso/issues/256

**Comment by kameshsampath** [comment]
WIP

**Comment by LalatenduMohanty** [comment]
Resolved via https://github.com/minishift/minishift-addons/pull/134

**Comment by gbraad** [comment]
Let's evaluate this after some manuak tests on our end to make/move this to
the minishift repo. WDYT?
