### ISSUE TITLE
Upcoming versions of Eclipse Che will remove oauth token option.

### ISSUE THREAD

**Issue by amisevsk** [minishift/minishift-addons#146]
As of PR https://github.com/eclipse/che/pull/10529, the Che property `che.infra.kubernetes.oauth_token` is no longer used. To avoid confusion, it should be removed from the Che minishift addon as well. 

Note that the addon works perfectly fine using the Che service account that is already created, so this shouldn't break anything (in fact, as tokens expire, it should make running Che somewhat easier).

**Comment by LalatenduMohanty** [comment]
@amisevsk Please open issues or pull requests for Che add-on in [Minishift repository](https://github.com/minishift/minishift/) as it is moved there.
Che is a default Minishift add-on now.
