### ISSUE TITLE
Broken links in READMEs of individual addons

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift-addons#33]
For example in `cockpit/README.md` there is a link to `general readme`, however this link is broken:
```url
https://github.com/minishift/minishift-addons/blob/master/Readme.adoc#download-and-use-community-add-ons
```
Instead the README should be in upper case in the link to work:
```
https://github.com/minishift/minishift-addons/blob/master/README.adoc#download-and-use-community-add-ons
```

**Comment by agajdosi** [comment]
Should be easy, will fix it today.

**Comment by LalatenduMohanty** [comment]
Fixed by https://github.com/minishift/minishift-addons/pull/34
