### ISSUE TITLE
Improvements for Che add-on to work on non-unix operating systems

### ISSUE THREAD

**Issue by JamesDrummond** [minishift/minishift-addons#60]
Love the addon for Che. Really solves the problem with having to run unix scripts on windows to get things working. However, the replace stacks should really be put in it's own addon so that host system does not need to be unix based for Che to work.

[https://github.com/minishift/minishift-addons/tree/master/add-ons/che#replace-che-stacks](https://github.com/minishift/minishift-addons/tree/master/add-ons/che#replace-che-stacks)

**Comment by LalatenduMohanty** [comment]
cc @sunix

**Comment by JamesDrummond** [comment]
Replace stacks is no longer needed in che 6/nightly branch to make default stacks work.
