### ISSUE TITLE
Che addon is failing with OpenShift 3.7.0

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift-addons#62]
### With OpenShift 3.6.0

```
$ minishift status
Minishift:  Running
Profile:    os_360
OpenShift:  Running (openshift v3.6.0+c4dd4cf)
DiskUsage:  11% of 17.9G

$ minishift addons apply che
-- Applying addon 'che':
[CHE] Create Image Stream.
[CHE] Create the Che server Template.
[CHE] Creating mini-che project.
[CHE] Switching to mini-che....
[CHE] Deploying Che on minishift.
Please wait while the pods all startup!
You can watch in the OpenShift console via:
  minishift console
Then you should be able the open the Che dashboard here:
  http://che-mini-che.192.168.42.21.nip.io
```

### With OpenShift 3.7.0
```
$ minishift status
Minishift:  Running
Profile:    os_370
OpenShift:  Running (openshift v3.7.0+7ed6862)
DiskUsage:  8% of 17.9G

$ minishift addon apply che
-- Applying addon 'che':
[CHE] Create Image Stream.
[CHE] Create the Che server Template.
[CHE] Creating mini-che project.Error from server (Forbidden): You may not request a new project via this API.
Error applying the add-on: Error executing command oc new-project mini-che --description="Eclipse Che on minishift" --as=developer.
```

**Comment by amitkrout** [comment]
Same issue reported in downstream https://issues.jboss.org/browse/CDK-207

**Comment by gbraad** [comment]
Please check: https://github.com/eclipse/che/issues/6097#issuecomment-351308112

This might be a general problem with Che on OpenShift

**Comment by LalatenduMohanty** [comment]
@sunix Do you know about the issue?

**Comment by sunix** [comment]
@LalatenduMohanty we had troubles on openshift.io with 3.7 not sure how it is related, will check with team

**Comment by ibuziuk** [comment]
@LalatenduMohanty @sunix the problem that we had with 3.7 on osio was infra related and was resolved by restarting controllers on master node [1]. This one is smth. different. Looks like there is some problem during project creation on minishift.

>  oc new-project mini-che --description="Eclipse Che on minishift" --as=developer


[1] https://github.com/openshiftio/openshift.io/issues/1666#issuecomment-351839391

**Comment by ibuziuk** [comment]
Just tested on the following `minishift openshift version`:

```
openshift v3.7.0-rc.0+e92d5c5
kubernetes v1.7.6+a08f5eeb62
etcd 3.2.8
```

Removing `--as=developer` from che.addon [1] applies it correctly. Wondering where this API change is documented on OpenShift side (`You may not request a new project via this API`)?

[1] https://github.com/minishift/minishift-addons/blob/master/add-ons/che/che.addon#L12

**Comment by ibuziuk** [comment]
PR with workaround https://github.com/minishift/minishift-addons/pull/68
