### ISSUE TITLE
Need a test framework to write tests for the add-ons

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift-addons#67]
The end goal is we should be able to test these add-ons against specific OpenShift and Minishift versions. Contributors should be able to contribute a test file which would test the add-on. Also we should be able to test these add-ons for each Minishift release in an automated way. 

This way we can maintain the quality of the repository and it will enable us to keep the add-ons in good shape.

**Comment by gbraad** [comment]
I believe we discussed to prefer using our test features as written in
Cucumber. Also, Mario @l0rd, had taken a glance at this and believes it
would be possible to get some basic tests for the Che plugin

**Comment by l0rd** [comment]
@LalatenduMohanty @gbraad we are working on a cucumber (godog) tests for Che addon. I believe @JPinkney is really close to open a PR.

**Comment by gbraad** [comment]
great news!

**Comment by agajdosi** [comment]
Hi @l0rd, I am working on PR which enables usage of Minishift integration tests as a package (https://github.com/minishift/minishift/issues/1970), once this PR is merged I will implement it in this repository (prove of concept works [agajdosi/minishift-addons:#67](https://github.com/agajdosi/minishift-addons/tree/67)).

After that @JPinkney can continue with PR for the Che addon. We are now the blocking part for the Che addon, trying to resolve it ASAP, thanks for understanding.

**Comment by l0rd** [comment]
Ok thank you @agajdosi for this update

**Comment by budhrg** [comment]
My idea of "Test framework" for minishift-addon repo.

As as first cut, we should able to `install` and `apply` as part of nightly build.
Create issue https://github.com/minishift/minishift/issues/1976 to introduce new field as `Maintainer` so that we know who is maintaining the addon and if CI fails for any particular addon, we should notify to the respective maintainer. 
We can automate the notification part as well.

**Comment by agajdosi** [comment]
@budhrg AFAIU we would ideally need one Minishift start per add-on to prevent any interferences between add-ons. As we plan to run the tests once per day it seems realistic to have it one start per add-on.

We could achieve it with Gherkin:

```gherkin
@cors
Feature: Cors Add-on 
  As Minishift user I can install and apply Cors add-on from minishift-addons repository.

  Scenario: Installing the add-on
     When file from "https://raw.githubusercontent.com/minishift/minishift-addons/master/add-ons/cors/cors.addon" is downloaded into location "download/cors"
      And executing "minishift addons install ../../out/integration-test/download/cors" succeeds
     Then stdout should contain "Addon 'cors' installed"

  Scenario: Minishift starts
    Given Minishift has state "Does Not Exist"
     When executing "minishift start" succeeds
     Then Minishift should have state "Running"

  Scenario: Applying the add-on
    Given Minishift has state "Running"
     When executing "minishift addons apply cors" succeeds
     Then stdout should contain "CORS is now allowed from any address"

  Scenario: Deleting Minishift
    Given Minishift has state "Running"
     When executing "minishift delete --force" succeeds
     Then Minishift should have state "Does Not Exist"
```

As this basic install&apply feature is relatively easy to read it could serve also as simple example for add-on developers which could encourage them to expand the test. WDYT?

**Comment by budhrg** [comment]
>  Scenario: Applying the add-on

Some of the addons like [Istio](https://github.com/minishift/minishift-addons/tree/master/add-ons/istio#preparing-istio) is tricky here and writing its feature file is not that easy. 
I think if we provide a framework where they can provide the tests in shell file then it is easy for us to run those tests.

**Comment by budhrg** [comment]
Resolved via https://github.com/minishift/minishift-addons/pull/85
