### ISSUE TITLE
update asb add-on for OpenShift 3.7.1

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift-addons#81]
https://github.com/minishift/minishift-addons/tree/master/add-ons/ansible-service-broker .  Refer https://github.com/minishift/minishift-addons/pull/76

- Update template to pull most recent template
- Pull templates from the upstream repo to ensure things stay up to
    date.
 - Added an additional template that will permit the developer user
    correctly so that it can support apb cli functionality.
  - Removed unnecessary templates/
  - Added updated docs now that this README.md is considered the golden
    source for documenting running the broker and its tooling with minishift

**Comment by budhrg** [comment]
Resolved via https://github.com/minishift/minishift-addons/pull/76
